### ISSUE TITLE
Move route guide example to RPC repository

### ISSUE THREAD

**Issue by AdrianRaFo** [frees-io/freestyle-rpc#222]
- [x] Create the examples structure #217
 - [x] Add protocol sbt module to the example #218
 - [x] Add service sbt module to the example #219
 - [x] Create the server module with the protocol #220
 - [x] Create the client module with the protocol #221
